### ISSUE TITLE
C-w doesn't work in phi-search if the keybinding is mapped to something other than kill-region.

### ISSUE THREAD

**Issue by milkypostman** [zk-phi/phi-search#38]
In my `init.el` I have `C-w` bound to `kill-region-or-backward-word` which does a kind of *dwim* of killing something that's highlighted or deleting the previous word when no mark is active. Unfortunately the way that bindings are setup in `phi-search` means that my `C-w` doesn't call `phi-search-yank-word`. 

Is there a reason to do the remapping rather than binding functions directly to their function? Like, is there a reason not to just bind `C-w` to `phi-search-yank-word`? I know I can do that now but I think the "aliasing" is a bit odd.

**Comment by zk-phi** [comment]
For those people who change the default Emacs keybinding. But, yes, binding `C-w` directly seems reasonable.
