### ISSUE TITLE
phi-search causes error when toggle-debug-on-error enabled

### ISSUE THREAD

**Issue by milkypostman** [zk-phi/phi-search#39]
I like to leave `toggle-debug-on-error` enabled, but when I use *phi-search* with this on, finding no matches shows an error. I realize this **is** an error technically but I don't think it should cause a full-blown error that triggers the debugging trace.

I'd be happy to help fix this or add a toggle for it. Let me know what you think.

**Comment by zk-phi** [comment]
Suppressing errors when called interactively seems reasonable (`next-line` in simple.el does so). I'll implement later, thanks for reporting.

**Comment by zk-phi** [comment]
fixed, thanks.

**Comment by milkypostman** [comment]
Thank you!
