### ISSUE TITLE
multiple-cursor and phi-search to set multiple cursor points

### ISSUE THREAD

**Issue by raguay** [zk-phi/phi-search#44]
Hi,

I just created a configuration layer for Spacemacs using multiple-cursor and phi-search. I want to be able to create multiple cursor points based on a regular expression search. The scenario that I have is to change all of the heading in a markdown file from section.lesson to just lesson number. For example:

 ## 1.1
 ## 2.1
 ## 2.2

changed to
 
 ## 1
 ## 2
 ## 3

There is lessons contents in between each heading. I use the regular expression ##\w*\d*\.\d* to select each area. Then delete, add the ## back, and auto-add numbers at each cursor point.

This is easy to do with Sublime Text and the Text Pastry module, but I would like to switch to Spacemacs only and can not figure this one out (Not wanting to pay the upgrade fee when 3 is out of beta and Vim emulation on Sublime is not as good). 

I have not used eLisp in over 30 years. I am a little rusty in it ;-)

**Comment by zk-phi** [comment]
`phi-search-mc` (https://github.com/knu/phi-search-mc.el) may be helpful for you.

**Comment by raguay** [comment]
Thanks. Now to add incremental number count at each cursor.

**Comment by Kaligule** [comment]
@raguay I am not even sure if this is a question, but for adding numbers at each cursor you could use `mc/insert-numbers` from the multiple-cursors library.
