### ISSUE TITLE
search for tabs

### ISSUE THREAD

**Issue by nha** [zk-phi/phi-search#45]
I am navigating what is basically a tab-delimited spreadsheet. I came across `multiple-cursors`, which requires `phi-search` when searching. But it seems I cannot insert tabs in the search text ? I get a [too short] message...

Is there a way to search for tabs ?

Thanks for multiple-cursors :)

**Comment by zk-phi** [comment]
Number of matches is limited in `phi-search` to prevent Emacs from hanging up, and it seems that the number of TABs in the buffer exceeds the limit. I know that I should implement something like "lazy matching", i.e. when the number of matches exceeds the limit, do not search further then, and further search will be done on-demand (as needed), but it's not implemented for now.

A possible workaround is to increase the limit by setting `phi-search-limit` (as described in Readme.org)

````
(setq phi-search-limit 10000)
````

**Comment by nha** [comment]
Oh thank you I misunderstood the `phi-search-limit` when reading the docs. I thought it was the limit after which no more results are returned (not the limit after which no results are returned) ?

Anyway thank you for answering me :)
