### ISSUE TITLE
Jumping window after pressing enter, when using with sublimity-scroll

### ISSUE THREAD

**Issue by MHOOO** [zk-phi/phi-search#48]
When...
1. I have sublimity-scroll enabled and then 
2. start a search with phi-search and then
3. search some word, until the view needs to scroll (either up or down) and
4. the currently selected item is either at the top or the bottom of the screen (i.e. not at the center),

then for some reason, after pressing enter (to finish the search), the screen jumps in such a way, that the item is either to the very top or very bottom of the screen. This can be very disorienting, as the eyes need to then scan the current buffer, to find the cursor again.
I'm using emacs 24.5.1, and sublimity & phi-search from git.

For me, my current fix, involves temporarily rebinding sublimity-mode to an identity fn and disabling it prior to searching with phi-search.

**Comment by zk-phi** [comment]
Sorry for super late reply, but I couldn't  reproduce the problem.
If you still have the problem, please reopen the issue with the condition that reproduces the problem.
